# Generated by Django 3.1.7 on 2021-03-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodigies', '0003_auto_20210330_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='due_time',
        ),
        migrations.AddField(
            model_name='todo',
            name='due_time',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
