# Generated by Django 3.1.7 on 2021-03-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodigies', '0006_auto_20210331_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='memo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
