# Generated by Django 3.1.7 on 2021-04-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodigies', '0007_auto_20210331_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='memo',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='memo',
            new_name='description',
        ),
    ]
