# Generated by Django 3.1.7 on 2021-04-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodigies', '0008_auto_20210410_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
