# Generated by Django 3.1.7 on 2021-04-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodigies', '0009_todo_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='desc',
        ),
    ]
