# Generated by Django 3.1.7 on 2021-04-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodigies', '0010_auto_20210410_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='link',
        ),
    ]
